//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        
        public int idLog { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        //metodos
        public static bool inicioSecion(String usuario,String clave)
        {
            JuzgadoEntities db = new JuzgadoEntities();
           
            var query = from lo in db.Log where lo.usuario.Equals(usuario) && lo.clave.Equals(clave) select lo;

            try
            {
                query.First();
                return true;
            }
            catch (Exception e)
            {
                return false;
               
            }
        }

    }
}
