//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuzgadoEntities : DbContext
    {
        public JuzgadoEntities()
            : base("name=JuzgadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Involucrados> Involucrados { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<procesosJudiciales> procesosJudiciales { get; set; }
        public virtual DbSet<Seguimientos> Seguimientos { get; set; }
        public virtual DbSet<tipoArreglo> tipoArreglo { get; set; }
        public virtual DbSet<tipoProceso> tipoProceso { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
