//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimientos
    {
        public int idSeguimiento { get; set; }
        public int procesoJudicial { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
        public int tipoArreglo { get; set; }
        public string estado { get; set; }
    
        public virtual procesosJudiciales procesosJudiciales { get; set; }
        public virtual tipoArreglo tipoArreglo1 { get; set; }
    }
}
