//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class tipoArreglo
    {
        public tipoArreglo()
        {
            this.Seguimientos = new HashSet<Seguimientos>();
        }
    
        public int idTipoArreglo { get; set; }
        public string tipoArreglo1 { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Seguimientos> Seguimientos { get; set; }
        public static IQueryable<tipoArreglo> selectAll(JuzgadoEntities db)
        {
            

            var query = from lo in db.tipoArreglo where lo.estado.Equals("activo") select lo;

            try
            {

                return query;
               
             
            }
            catch (Exception e)
            {
                return null;

            }
        }
    }
}
