//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class tipoProceso
    {
        public tipoProceso()
        {
            this.procesosJudiciales = new HashSet<procesosJudiciales>();
        }
    
        public int idTipoProceso { get; set; }
        public string tipoProceso1 { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<procesosJudiciales> procesosJudiciales { get; set; }

        public static IQueryable<tipoProceso> selectAll(JuzgadoEntities db)
        {


            var query = from lo in db.tipoProceso where lo.estado.Equals("activo") select lo;

            try
            {

                return query;


            }
            catch (Exception e)
            {
                return null;

            }
        }
        public static bool verificarActivos(JuzgadoEntities db)
        {


            int numero = (from lo in db.tipoProceso where lo.estado == "activo" select lo).Count();

            try
            {

                if (numero > 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }



            }
            catch (Exception e)
            {
                return false;

            }
        }
    }
}
