//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace juzgado.Modelos
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Involucrados = new HashSet<Involucrados>();
        }
    
        public int idUsuario { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string tipoDocumento { get; set; }
        public string documento { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Involucrados> Involucrados { get; set; }
        public static IQueryable<Usuarios> selectAll(JuzgadoEntities db)
        {


            var query = from lo in db.Usuarios where lo.estado.Equals("activo") select lo;
            
            try
            {

     
                return query;
                

            }
            catch (Exception e)
            {
                return null;

            }
        }
        public static bool verificarDocumento(JuzgadoEntities db,int idUsuario,String documento)
        {
             

            int numero = (from lo in db.Usuarios where lo.estado == "activo" && lo.idUsuario != idUsuario && lo.documento == documento select lo).Count();

            try
            {

                if (numero > 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }



            }
            catch (Exception e)
            {
                return false;

            }
        }


        public static IQueryable<Usuarios> buscarPorDocumento(JuzgadoEntities db, string documento)
        {


            var query = from lo in db.Usuarios where lo.estado.Equals("activo") && lo.documento.Contains(documento) select lo;

            try
            {


                return query;


            }
            catch (Exception e)
            {
                return null;

            }
        }

    }
}
